#!/usr/bin/env node
// A simple service wrapper around the SauceLabs Connect.
var BgRunner = require('bg-runner')
  , path = require('path')
  ;

sauceLabsConnect = new BgRunner({
  name:         "SauceLabs Connect",
  label:        "saucelabs-connect",
  command:      "java",
  hasReadyFile: "yes",
  wait:         true,
  timeout:      120000
});

// Add the stock command line args to the provide access key and secret.
sauceLabsConnect.on('beforeStart', function(e) {
  var jarFile = path.resolve(path.join(__dirname, '..', 'tools', 'saucelabs-connect', 'Sauce-Connect.jar'));
  var logFile = path.resolve(path.join(e.config.root, 'var', 'log', e.config.label, 'log.txt'));
  e.args = [
    '-jar',
    jarFile
  ].concat(e.args).concat([
      '-f',
      e.config.readyFile,
      '-l',
      logFile
    ]);
});

sauceLabsConnect.run(process.argv.slice(2));
