#!/usr/bin/env node
// A simple service wrapper around the test site.
var BgRunner = require('bg-runner')
  , path = require('path')
  , Tail = require('tail').Tail
  ;

testsite = new BgRunner({
  name:         "Test Site",
  label:        "testsite",
  command:      path.resolve(path.join(__dirname, 'web.js')),
  hasReadyFile: "yes",
  wait:         true,
  timeout:      5000
});

// Ugh, need to tail the log file to see if we get a "Listening at" in order
// to determine the test site is indeed responsive.
testsite.on('beforeStart', function(e) {
  var tail = new Tail(e.config.outFile);
  tail.on('line', function(line) {
    if (line.indexOf('Listening at') == 0) {
      e.writeReadyFile();
    }
  });
});

testsite.run(process.argv.slice(2));
