#!/usr/bin/env node

// initialize express application
var fs, app, root, path, port, https, express;

// dependencies
fs = require('fs');
https = require('https');
express = require('express');
app = express();

// handle relative paths properly
path = require('path');
root = path.dirname(module.filename);

// use express logger to show info
// about all incoming requests
app.use(express.logger());

// setup paths to serve static files from
// use relative path from binary to provide
// robust way for finding files
app.use(express.static(path.join(root, '../target/script')));
app.use(express.static(path.join(root, '../target/style')));
app.use(express.static(path.join(root, '../source/script')));
app.use(express.static(path.join(root, '../source/style')));
app.use(express.static(path.join(root, '../tests/pages')));

// detect what port number use for server
port = process.env.PORT || process.argv[2] || 8000;

// start http server (express app) on specified port
app.listen(port, function(){
	console.log('started on http://localhost:' + port + '/');
});

// if https ontion passed to script
if (['yes', 'on', 'true'].indexOf(process.argv[3]) >=0){
	// create https server and start it on 443 port
	https.createServer({
		key:	fs.readFileSync('binary/cert/localhost.key'),
		cert:	fs.readFileSync('binary/cert/localhost.cert')
	}, app).listen(443, function(){
		console.log('started on https://localhost/');
	});
}