  /**
   * Customer-Customization File
   * This file is used to deliver a custom customer customization.
   *   
   *   USAGE:
   *   
   *     1 - DO NOT EDIT THIS FILE!
   *     2 - Create a Customization ID for use with your customization.
   *
   *            Your Customization-ID is created like this: 
   *            
   *                "custom_[site--id]_[JIRA-issue-number]"
   *
   *            For example the full Customization-ID should appear like this:
   *            
   *                "custom_FFF123_EQ-1234"
   * 
   *     3 - Copy this file into to the customization directory, using your Customization-ID:
   *
   *            Example: "source/js/customizations/custom_FFF123_EQ-1234.js"         
   * 
   *     4 - Fill out the CUSTOMIZATION-DESCRIPTION below dashed line.
   *     6 - Follow the comments below the dotted line, making sure you fill in the blanks
   *
   *   -----------------------------------------------------------------------------------------------
   *   
   *   CUSTOMIZATION-DESCRIPTION: (FILLED BY ENGINEER)
   *   
   *   [
   *     Write the description of what the customization does in here. Example: "This customization
   *     fixes problems with overflow:hidden elements on EEOC.gov by updating the CSS rules of some
   *     elements of the home-page."
   *   ]
   *
   *   ...............................................................................................
   *   
   *   CUSTOMIZATION-SCRIPT: (ALSO FILLED BY ENGINEER)
   * 
   */

  // 7 - Insert your Customization-ID in BOTH places parts of the def() statement...
  sitecues.def('[Customization-ID]', function ([Customization-ID], callback, log) {

    // 8 - Insert your [module-to-customize] and your [required-modules] in the use() statement below...
    // 
    //     Eg:
    //     
    //     sitecues.use('customization', 'picker', 'jquery', function (customization, picker, jquery) {
    //     
    sitecues.use('customization', '[module-to-customize]', '[required-module-1]', '[required-module-2]', function (customization, module_to_customize, required_module_1, required_module_2) {

      customization.register({
        
        // 9 - Insert the [module-to-customize] for the module that the customization should run in.
        //          You can find the [module-to-customize] name in the def() statement of the module
        //          that you want to customize.
        //          
        //          Eg:
        //          
        //          moduleName: 'picker',
        //          
        module: '[module-name]',
        
        // 11 - Insert the Customization-ID] here.
        customId: '[Customization-ID]',

        func: function (event) {
          
          // 12 - Insert your customization code here. This function runs AFTER the module is loaded.

        }
          
      });

      callback();
    })
  });

  // 13 - Include a reference to your customization file in the makefile.

