define([
  'page/keys/keys',
  'page/keys/commands',
  'page/util/element-classifier',
  'page/highlight/highlight',
  'page/util/common',
  'page/highlight/move-keys',
  'page/zoom/zoom',
  'page/hpan/hpan',
  'page/zoom/fixed-position-fixer',
  'page/focus/focus',
  'page/cursor/cursor',
  'page/zoom/util/body-geometry',
  'page/zoom/util/restrict-zoom',
  'page/zoom/util/viewport',
  'page/zoom/config/config',
  'page/zoom/animation',
  'page/zoom/constants',
  'page/zoom/state'
  ], function() { }
);
