python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_0.ico -x 0 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_0.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_1.ico -x 1 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_1.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_2.ico -x 2 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_2.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_3.ico -x 3 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_3.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_4.ico -x 4 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_4.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_5.ico -x 5 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_5.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_6.ico -x 6 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_6.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_7.ico -x 7 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_7.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_8.ico -x 8 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_8.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_9.ico -x 9 -y 0 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_9.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_10.ico -x 10 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_10.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_11.ico -x 11 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_11.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_12.ico -x 12 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_12.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_13.ico -x 13 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_13.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_14.ico -x 14 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_14.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_15.ico -x 15 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_15.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_16.ico -x 16 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_16.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_17.ico -x 17 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_17.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_18.ico -x 18 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_18.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_19.ico -x 19 -y 1 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_19.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/min-osx-retina-arrow-ds.svg_20.ico -x 20 -y 2 -f ./cursor_output/cur/min-osx-retina-arrow-ds.svg_20.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_0.ico -x 0 -y 0 -f ./cursor_output/cur/hand-min-retina.svg_0.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_1.ico -x 5 -y 5 -f ./cursor_output/cur/hand-min-retina.svg_1.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_2.ico -x 10 -y 10 -f ./cursor_output/cur/hand-min-retina.svg_2.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_3.ico -x 15 -y 15 -f ./cursor_output/cur/hand-min-retina.svg_3.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_4.ico -x 20 -y 20 -f ./cursor_output/cur/hand-min-retina.svg_4.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_5.ico -x 25 -y 25 -f ./cursor_output/cur/hand-min-retina.svg_5.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_6.ico -x 30 -y 30 -f ./cursor_output/cur/hand-min-retina.svg_6.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_7.ico -x 35 -y 35 -f ./cursor_output/cur/hand-min-retina.svg_7.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_8.ico -x 40 -y 40 -f ./cursor_output/cur/hand-min-retina.svg_8.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_9.ico -x 45 -y 45 -f ./cursor_output/cur/hand-min-retina.svg_9.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_10.ico -x 50 -y 50 -f ./cursor_output/cur/hand-min-retina.svg_10.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_11.ico -x 55 -y 55 -f ./cursor_output/cur/hand-min-retina.svg_11.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_12.ico -x 60 -y 60 -f ./cursor_output/cur/hand-min-retina.svg_12.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_13.ico -x 65 -y 65 -f ./cursor_output/cur/hand-min-retina.svg_13.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_14.ico -x 70 -y 70 -f ./cursor_output/cur/hand-min-retina.svg_14.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_15.ico -x 75 -y 75 -f ./cursor_output/cur/hand-min-retina.svg_15.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_16.ico -x 80 -y 80 -f ./cursor_output/cur/hand-min-retina.svg_16.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_17.ico -x 85 -y 85 -f ./cursor_output/cur/hand-min-retina.svg_17.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_18.ico -x 90 -y 90 -f ./cursor_output/cur/hand-min-retina.svg_18.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_19.ico -x 95 -y 95 -f ./cursor_output/cur/hand-min-retina.svg_19.cur 
python ./res/ico2cur/ico2cur.py ./cursor_output/ico/hand-min-retina.svg_20.ico -x 100 -y 100 -f ./cursor_output/cur/hand-min-retina.svg_20.cur 
